### ISSUE TITLE
make/build fails

### ISSUE THREAD

**Issue by adeliktas** [aDakic/virtual_hmi#7] opened 2021-12-03 17:00 UTC
cmake . && make

[ 21%] Built target fmt
[ 28%] Building CXX object CMakeFiles/uinput.dir/src/system/file_desc.cpp.o
error: too many errors emitted, stopping now [clang-diagnostic-error]
~/Downloads/uinput/include/uinput/system/file_desc.hpp:17:30: error: no type named 'string_view' in namespace 'std' [clang-diagnostic-error]
        file_desc(const std::string_view path, access_mode_t access_mode);
                        ~~~~~^
~/Downloads/uinput/include/uinput/system/file_desc.hpp:17:48: error: unknown type name 'access_mode_t' [clang-diagnostic-error]
        file_desc(const std::string_view path, access_mode_t access_mode);
                                               ^
~/Downloads/uinput/include/uinput/system/file_desc.hpp:29:15: error: unknown type name 'native_handle_t' [clang-diagnostic-error]
        const native_handle_t& native_handle() const noexcept;
              ^
~/Downloads/uinput/include/uinput/system/file_desc.hpp:38:23: error: no template named 'opt_buffer_t'; did you mean 'buffer_t'? [clang-diagnostic-error]
        [[nodiscard]] opt_buffer_t<T, N> read() const noexcept;
                      ^~~~~~~~~~~~
                      buffer_t
~/Downloads/uinput/include/uinput/system/file_desc_defines.hpp:13:5: note: 'buffer_t' declared here
    using buffer_t = std::array<T, N>;
    ^
~/Downloads/uinput/include/uinput/system/file_desc.hpp:41:23: error: no template named 'opt_t' [clang-diagnostic-error]
        [[nodiscard]] opt_t<T> read() const noexcept;
                      ^
~/Downloads/uinput/include/uinput/system/file_desc.hpp:47:9: error: unknown type name 'native_handle_t' [clang-diagnostic-error]
        native_handle_t m_fd{ -1 };
        ^
~/Downloads/uinput/include/uinput/system/file_desc.hpp:81:5: error: no template named 'opt_buffer_t'; did you mean 'buffer_t'? [clang-diagnostic-error]
    opt_buffer_t<T, N> file_desc::read() const noexcept
    ^~~~~~~~~~~~
    buffer_t
~/Downloads/uinput/include/uinput/system/file_desc_defines.hpp:13:5: note: 'buffer_t' declared here
    using buffer_t = std::array<T, N>;
    ^
~/Downloads/uinput/include/uinput/system/file_desc.hpp:98:5: error: no template named 'opt_t' [clang-diagnostic-error]
    opt_t<T> file_desc::read() const noexcept
    ^
~/Downloads/uinput/include/uinput/system/file_desc_defines.hpp:10:29: error: no type named 'int32_t' in namespace 'std'; did you mean '__int32_t'? [clang-diagnostic-error]
    using native_handle_t = std::int32_t;
                            ^~~~~~~~~~~~
                            __int32_t
/usr/include/bits/types.h:41:20: note: '__int32_t' declared here
typedef signed int __int32_t;
                   ^
~/Downloads/uinput/include/uinput/system/file_desc_defines.hpp:16:24: error: no template named 'optional' in namespace 'std' [clang-diagnostic-error]
    using opt_t = std::optional<T>;
                  ~~~~~^
~/Downloads/uinput/include/uinput/system/file_desc_defines.hpp:19:31: error: no template named 'optional' in namespace 'std' [clang-diagnostic-error]
    using opt_buffer_t = std::optional<buffer_t<T, N>>;
                         ~~~~~^
~/Downloads/uinput/include/uinput/system/file_desc_defines.hpp:21:43: error: no member named 'nullopt' in namespace 'std' [clang-diagnostic-error]
    inline constexpr auto opt_null = std::nullopt;
                                     ~~~~~^
~/Downloads/uinput/include/uinput/system/file_desc_defines.hpp:23:49: error: no type named 'int32_t' in namespace 'std'; did you mean '__int32_t'? [clang-diagnostic-error]
    using access_mode_t                       = std::int32_t;
                                                ^~~~~~~~~~~~
                                                __int32_t
/usr/include/bits/types.h:41:20: note: '__int32_t' declared here
typedef signed int __int32_t;
                   ^
~/Downloads/uinput/include/uinput/system/file_desc_defines.hpp:24:22: error: unknown type name 'access_mode_t' [clang-diagnostic-error]
    inline constexpr access_mode_t read_only  = O_RDONLY;
                     ^
~/Downloads/uinput/include/uinput/system/file_desc_defines.hpp:25:22: error: unknown type name 'access_mode_t' [clang-diagnostic-error]
    inline constexpr access_mode_t read_write = O_RDWR;
                     ^
~/Downloads/uinput/include/uinput/system/file_desc_defines.hpp:26:22: error: unknown type name 'access_mode_t' [clang-diagnostic-error]
    inline constexpr access_mode_t write_only = O_WRONLY;
                     ^
~/Downloads/uinput/include/uinput/system/file_desc_defines.hpp:27:22: error: unknown type name 'access_mode_t' [clang-diagnostic-error]
    inline constexpr access_mode_t non_block  = O_NONBLOCK;
                     ^
~/Downloads/uinput/include/uinput/system/file_desc_defines.hpp:28:22: error: unknown type name 'access_mode_t' [clang-diagnostic-error]
    inline constexpr access_mode_t no_delay   = O_NDELAY;
                     ^
~/Downloads/uinput/src/system/file_desc.cpp:7:37: error: no type named 'string_view' in namespace 'std' [clang-diagnostic-error]
    file_desc::file_desc(const std::string_view path, access_mode_t access_mode)
                               ~~~~~^
9 warnings and 20 errors generated.
Error while processing ~/Downloads/uinput/src/system/file_desc.cpp.
Suppressed 9 warnings (9 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).
make[2]: *** [CMakeFiles/uinput.dir/build.make:76: CMakeFiles/uinput.dir/src/system/file_desc.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:123: CMakeFiles/uinput.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

same issue with: mkdir build && cmake .. && make

i don't know how to further proceed. Any help is appreciated, thanks in advance.

**Comment by aDakic** [comment] 2021-12-13 11:25
Hi,
Sorry for the late response, I was on a vacation :)
I can't reproduce the issue on my VM. What a compiler (and version) do you use?
Please note that the compiler must support C++17 features.

**Comment by adeliktas** [comment] 2021-12-14 01:10
Hello, thanks for the hint, i was able to solve this issue.
it's gcc/g++ (Gentoo 11.2.0 p1) 11.2.0 , by default cmake uses CXX_STANDARD: 11 for the Makefile, so i specified it in ./uinput/CMakeLists.txt with set (CMAKE_CXX_STANDARD 17) before "set(headers..." and had to add:
```
#include <cstdint>
#include <stdexcept>
#include <limits>
```
in ./uinput/include/uinput/uinput_defines.hpp
because the type definitions are not by default part of the namespace std.
So i was able to compile, but i haven't done any further tests. I will check it out on the weekend and possibly create a PR.

**Comment by aDakic** [comment] 2021-12-14 09:46
the PR has been merged, closing the issue.

**Closed as completed by aDakic** 2021-12-14 09:46 UTC
